pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt
      - python setup.py install
  
  pypi_publish:
    image: gjtempleton/drone-pypi
    repository: https://pypi.python.org/pypi
    username: $${PYPI_LOGIN}
    password: $${PYPI_PASSWORD}
    secrets: [ pypi_login, pypi_password ]
