pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:        
        - pip install -r requirements.txt
        - python setup.py install
        
  publish: 
    build:
      image: python:3.6
      commands:        
          - pip install -r requirements.txt
          - python setup.py install

    pypi_publish:
      image: gjtempleton/drone-pypi
      username: pypi_login
      password: pypi_password
      secrets: [ pypi_login, pypi_password ]
 
matrix:
  PYTHON_VERSION:
    - 3.4
    - 3.5
    - 3.6
