pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt
      - python setup.py install
  
  pypi_publish:
    image: skar404/drone-pypi:latest
    secrets: [ PYPI_REPOSITORY, PYPI_USERNAME, PYPI_PASSWORD ]
