pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt
      - python setup.py install
      - pytest
 
  pypi_publish:
    image: username502/drone-pypi:latest
    secrets: [ PYPI_REPOSITORY, PYPI_USERNAME, PYPI_PASSWORD ]
    when:
      branch: master
      event: tag
