pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt
      - python setup.py install

  pypi_publish:
    image: gjtempleton/drone-pypi
    username: pypi_password
    password: pypi_password
    repository: https://upload.pypi.org/legacy/
    secrets: [ pypi_login, pypi_password ]
