pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt
      - python setup.py install
      - echo $${PYPI_LOGIN}
    secrets: [ pypi_login, pypi_password ]
    
  pypi_publish:
    image: gjtempleton/drone-pypi
    repository: https://upload.pypi.org/legacy/
    username: $${PYPI_LOGIN}
    password: $${PYPI_PASSWORD}
    secrets: [ pypi_login, pypi_password ]
