pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
        - echo ${TEST}
        - echo $${TEST}
        - echo $TEST
        - echo $test
        - echo ${test}
        
        - pip install -r requirements.txt
        - python setup.py install
    secrets: [ test ]
matrix:
  PYTHON_VERSION:
    - 3.4
    - 3.5
    - 3.6
