pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
        - echo ${TEST}
        - pip install -r requirements.txt
        - python setup.py install
    when:
      event: deployment
      environment: staging

matrix:
  PYTHON_VERSION:
    - 3.4
    - 3.5
    - 3.6
