pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
        - pip install -r requirements.txt
        - python setup.py install

matrix:
  PYTHON_VERSION:
    - 3.4
    - 3.5
    - 3.6
