pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt
      - python setup.py install
  
  test: 
     commands:        
      - pip install pytest
      - pytest
    secrets: [ marilyn_url_api, marilyn_login, marilyn_password ]
    when:
      branch: [master, dev]
    
  pypi_publish:
    image: username502/drone-pypi:latest
    secrets: [ PYPI_REPOSITORY, PYPI_USERNAME, PYPI_PASSWORD ]
    when:
      branch: master
      event: tag
