language: python
cache: pip
python:
 - '3.4'
 - '3.5'
 - '3.6'
install:
 - pip install pytest
 - pip install -r requirements.txt
 - python setup.py -q install
script:
 - pytest
notifications:
 email: true

jobs:
  include:
    - stage: deploy
      python: '3.6'
      deploy:
        provider: pypi
        user: skar404
        password:
          secure: IpRx4aqUVPuERNiMwweZcBtcnnJYEZgG+zzHlhSI1qk771eSZtRZAtTqUn5NXPFRIwuFChEQNsNYVe4a6Dsff1Jikf7r0acOyfIO/UkdjRoMZ91Nfj6r+JEWKFKZ79GyJkRvOn1L2tIto8irVUYgDUToAoeHX5nn+JJKLipoPeW18gB7Cyc6iiGJjUrRgo5as47Vkqm7FSrfEN+En8c9AKU5wSEfkASVKel9zxMeAYkhqXo3MOlkxH2czonXFIa0RSw58ut0+IzluT8wjLrkDJU+Zw6DuBjYKcQFF7Sp6gztmVjIds53P8Q+5YrZK5m7ESiWQ6eJWjFfPhjING6qpzONHGLJcKC69RFOBHWm1aQTC2/jZTjORg+3Jg+8qfxUhXvdf8bJIZ8NcMtwOonV24jUqHELAyE2wZOOh/aOADuf6HkyFCo5I3oiQWct8gcYVay2N6PqbeZbJPTUM4R+wIqg3mJ5hOkq9dEAaQj5a5A6qy8Fa0XY6puGQ67NEiHEct8MLqLWdWi5ghQZLaoSxWQim0sjIqQbvfJThAS1i0Zj/fCUSmH0XhUDWLvu4pGZCi8lXVE4JRexrsdemrYVbn5mDxtJG6MAeBtAKYhQQwekMC4dEa3Fda4gyTw9lLeGmO6wc5Skc19L1ehSq1nOlVxMTGwGE3vU7z4aHPhsmdA=
        on:
          distributions: sdist bdist_wheel
          repo: skar404/marilyn
          tags: true
